### ISSUE TITLE
Doxygen Build Error with 1.14.0: Failing to Find '@copydoc' Targets

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#4030]
CI has been failing on main since #6e2097e29270bf6dcaf3e971cbe6ce8d3d59e697, which is first commit where the runners were using Doxygen 1.14.0. The commit right before it was using Doxygen 1.13.2.

These are the exact failures from the log:
```
/Users/runner/work/ice/ice/cpp/include/Ice/NativePropertiesAdmin.h:35: error: @copybrief or @copydoc target 'PropertiesAdmin::setProperties' not found
/Users/runner/work/ice/ice/cpp/include/Ice/NativePropertiesAdmin.h:32: error: @copybrief or @copydoc target 'PropertiesAdmin::getPropertiesForPrefix' not found
/Users/runner/work/ice/ice/cpp/include/Ice/NativePropertiesAdmin.h:29: error: @copybrief or @copydoc target 'PropertiesAdmin::getProperty' not found
```

Notes:
1) `PropertiesAdmin` (and the referenced functions) do exist, but they're generated code.
2) I checked the docs generated with 1.13.2, and the `copydoc` tags were working correctly there. So it's not like this has always been broken, and Doxygen just added better validation or something.
3) Doxygen can find the file just fine. Changing a link from `@copydoc PropertiesAdmin::setProperties` to `@copydoc PropertiesAdmin::dispatch` results in doxygen finding the comment just fine. It's something specific to these functions.
4) Also, if you look at the current docs: https://code.zeroc.com/ice/main/api/cpp/namespaceIce.html, Doxygen doesn't seem to generate documentation for the generated `PropertiesAdmin`.

**Comment by externl** [comment]
We exclude it specially so I'm not surprised it doesn't work.

https://github.com/zeroc-ice/ice/blob/044e0ebd5febca13c0453555e1b63fdfe7621076/cpp/doxygen/Doxyfile#L1044
