### PR TITLE
Fix issue with Clang 13

### LINKED ISSUE #1352: 3.7.7: Failure to build on Mac OS
**Version(please complete the following information):**
 - Ice Version 3.7.7
 - OS: macOS 12.3
 - Distribution: none

Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0

**Describe the bug**
src/Slice/MD5I.cpp:175:25: error: performing pointer subtraction with a null pointer may have undefined behavior [-Werror,-Wnull-pointer-subtraction]
            if (!((data - (const md5_byte_t *)0) & 3)) {
                        ^ ~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Expected behavior**
No error

**Additional context**
Built fine before updating to clang 13.1.6

### PR DESCRIPTION
**Pull request by bold84**
Fixes #1352

### CODE REVIEW

**Comment by externl** [comment]
Hi @bold84, thanks for the PR. 

This change fails to compile on `gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)` due to a (conditionally) missing include for `stdint.h`.

```
[vagrant@el7-dev-a32c9344 ice]$ make
making all in cpp
make[1]: Entering directory `/home/vagrant/workspace/ice/cpp'
Compiling [x64-static] src/Slice/MD5I.cpp
src/Slice/MD5I.cpp: In function 'void md5_process(md5_state_t*, const md5_byte_t*)':
src/Slice/MD5I.cpp:175:37: error: expected type-specifier before 'uintptr_t'
             if (!((reinterpret_cast<uintptr_t>(data)) & 3))
                                     ^
src/Slice/MD5I.cpp:175:37: error: expected '>' before 'uintptr_t'
src/Slice/MD5I.cpp:175:37: error: expected '(' before 'uintptr_t'
src/Slice/MD5I.cpp:175:37: error: 'uintptr_t' was not declared in this scope
src/Slice/MD5I.cpp:176:13: error: expected ')' before '{' token
             {
             ^
src/Slice/MD5I.cpp:184:9: error: expected primary-expression before '}' token
         }
         ^
src/Slice/MD5I.cpp:184:9: error: expected ';' before '}' token
make[1]: *** [src/Slice/build/x64/static/MD5I.o] Error 1
```

**Comment by bold84** [comment]
> Hi @bold84, thanks for the PR.
> 
> This change fails to compile on `gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)` due to a (conditionally) missing include for `stdint.h`.
> 
> ```
> [vagrant@el7-dev-a32c9344 ice]$ make
> making all in cpp
> make[1]: Entering directory `/home/vagrant/workspace/ice/cpp'
> Compiling [x64-static] src/Slice/MD5I.cpp
> src/Slice/MD5I.cpp: In function 'void md5_process(md5_state_t*, const md5_byte_t*)':
> src/Slice/MD5I.cpp:175:37: error: expected type-specifier before 'uintptr_t'
>              if (!((reinterpret_cast<uintptr_t>(data)) & 3))
>                                      ^
> src/Slice/MD5I.cpp:175:37: error: expected '>' before 'uintptr_t'
> src/Slice/MD5I.cpp:175:37: error: expected '(' before 'uintptr_t'
> src/Slice/MD5I.cpp:175:37: error: 'uintptr_t' was not declared in this scope
> src/Slice/MD5I.cpp:176:13: error: expected ')' before '{' token
>              {
>              ^
> src/Slice/MD5I.cpp:184:9: error: expected primary-expression before '}' token
>          }
>          ^
> src/Slice/MD5I.cpp:184:9: error: expected ';' before '}' token
> make[1]: *** [src/Slice/build/x64/static/MD5I.o] Error 1
> ```

Okay, I will setup a CentOS VM later tonight and fix it. :-)
Or can you confirm that just including stdint.h safely resolves this issue? 

Kind regards,

Ben

**Comment by externl** [comment]
> Thank you for your response. I can setup a CentOS VM later tonight and fix it. :-) Or can you confirm that just including stdint.h safely resolves this issue?

Yep, just including it should be fine!

File: cpp/src/Slice/MD5I.cpp [hunk 1]
```diff
@@ -172,7 +173,7 @@ md5_process(md5_state_t *pms, const md5_byte_t *data /*[64]*/)
              * On little-endian machines, we can process properly aligned
              * data without copying it.
              */
-            if (!((reinterpret_cast<uintptr_t>(data)) & 3)) {
+            if (!((data - (const md5_byte_t *)0) & 3)) {
```
Comment (externl) [inline cpp/src/Slice/MD5I.cpp:176]: The `reinterpret_cast` is still needed here! The include is required for some compilers that can't find `uintptr_t`

Comment (bold84) [reply cpp/src/Slice/MD5I.cpp:176]: Oh, that was accidental (made a mistake with git). I'll re-apply.

**Review by pepone — APPROVED** [review]
Looks good to me!

**Review by externl — APPROVED** [review]
Looks good!
