### ISSUE TITLE
fails to build with openssl 3.0

### ISSUE THREAD

**Issue by jbicha** [zeroc-ice/ice#1319]
**Version**
 - Ice Version 3.7.6
 - OS: Linux
 - Distribution: Ubuntu 22.04 Alpha

**Describe the bug**

zeroc-ice [fails to build ](https://launchpad.net/ubuntu/+source/zeroc-ice/3.7.6-2) with openssl 3.0 which Ubuntu's development version has switched to using. The new major openssl release introduces new deprecations.

```
src/Ice/SHA1.cpp: In constructor ‘IceInternal::SHA1::Hasher::Hasher()’:
src/Ice/SHA1.cpp:98:14: error: ‘int SHA1_Init(SHA_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   98 |     SHA1_Init(&_ctx);
      |     ~~~~~~~~~^~~~~~~
In file included from src/Ice/SHA1.cpp:14:
/usr/include/openssl/sha.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
      |                           ^~~~~~~~~
src/Ice/SHA1.cpp: In member function ‘void IceInternal::SHA1::Hasher::update(const unsigned char*, size_t)’:
src/Ice/SHA1.cpp:113:16: error: ‘int SHA1_Update(SHA_CTX*, const void*, size_t)’ is deprecated:
 Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  113 |     SHA1_Update(&_ctx, reinterpret_cast<const void*>(data), length);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Ice/SHA1.cpp:14:
/usr/include/openssl/sha.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~~
src/Ice/SHA1.cpp: In member function ‘void IceInternal::SHA1::Hasher::finalize(std::vector<unsigned char>&)’:
src/Ice/SHA1.cpp:132:15: error: ‘int SHA1_Final(unsigned char*, SHA_CTX*)’ is deprecated:
Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  132 |     SHA1_Final(&md[0], &_ctx);
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from src/Ice/SHA1.cpp:14:
/usr/include/openssl/sha.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
      |                           ^~~~~~~~~~
mv -f  src/Ice/build/x86_64-linux-gnu/shared/pic/Selector.Td
  src/Ice/build/x86_64-linux-gnu/shared/pic/Selector.cpp.d
x86_64-linux-gnu-g++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects
 -fstack-protector-strong -Wformat -Werror=format-security -MT
 src/Ice/build/x86_64-linux-gnu/shared/pic/SliceChecksums.o -MMD
 -MP -MF  src/Ice/build/x86_64-linux-gnu/shared/pic/SliceChecksums.Td -Wall -Wextra -Wredundant-decls
 -Wshadow -Wdeprecated -Werror -pthread -DNDEBUG -Isrc -Isrc/Ice/generated -Iinclude -Iinclude/generated
 -DICE_BUILDING_SRC -DICE_API_EXPORTS -DICE_USE_SYSTEMD -fPIC -fvisibility=hidden
 -Wdate-time -D_FORTIFY_SOURCE=2 -c src/Ice/SliceChecksums.cpp -o
 src/Ice/build/x86_64-linux-gnu/shared/pic/SliceChecksums.o
cc1plus: all warnings being treated as errors
```

**Comment by pepone** [comment]
Thanks for reporting this @jbicha, I will look into it.

**Comment by pepone** [comment]
Hi, @jbicha 

Installed 22.04 but it comes with OpenSSL 1.1.1l installed, how do you upgrade to 3.x?

**Comment by pepone** [comment]
I found the packages in https://launchpad.net/~schopin/+archive/ubuntu/openssl-3.0.0

**Comment by pepone** [comment]
Fixed in #1320, uploaded 3.7.6-3 package to debian with a patch for IceSSL 3.0 see https://github.com/zeroc-ice/ice-debian-packaging/commit/ca7c59e2bc50c280cbc0af69efb54deba66848c1
